{% set name = "pyriemann" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd492b9373240ccbf25c099f05fa94c065cd13a9a3495be14d87989a52bea770

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn >=0.17
    - pandas
    - joblib
    - mne-base
    - matplotlib-base
    - seaborn

test:
  imports:
    - pyriemann
    - pyriemann.classification
    - pyriemann.clustering
    - pyriemann.embedding
    - pyriemann.estimation
    - pyriemann.spatialfilters
    - pyriemann.stats
    - pyriemann.tangentspace
    - pyriemann.utils
    - pyriemann.utils.covariance
    - pyriemann.utils.distance
    - pyriemann.utils.mean
    - pyriemann.utils.viz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pyriemann.readthedocs.io/en/latest/
  summary: Biosignals classification with Riemannian Geometry
  description: |
    pyRiemann aims at being a generic package for multivariate signal
    classification but has been designed around applications of biosignal
    (M/EEG, EMG, etc) classification.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/pyRiemann/pyRiemann

extra:
  recipe-maintainers:
    - larsoner
    - hoechenberger
